name: retrieve AWS secrets and manager
run-name: Running retrieve ${{ github.actor }}


on:
 pull_request:
   branches:
     - Dev

jobs:
  AWS-login:
     runs-on: ubuntu-latest

     steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: Retrieve secrets
        run: |
          secret_object=$(aws secretmanager get-secret-value --secret-id aboutStephen --query SecretString --output json)
          echo "$secret_object" | sed -n 's/.*\\"hobby\\":\\"\([^\\"]*\)\\".*/\1/p'
      
      - name: Retrieve parameter
        run: |
          aws ssm get-parameter --name /stephen/details --query Parameter.Value --output text
